LogFilePath: ../go_discord_dify_logs
clearCmd: clear chat history
clearCmdDesc: Clear the conversation context with ${botName}.
clearDelimiter: (The chat history between you and the robot has been cleared.)
freeChatLimit: -1
onAt: true